FROM nginx:1.11-alpine

# COPY resource/abc.html /usr/share/nginx/html/abc.html
# RUN rm /usr/share/nginx/html/index.html
EXPOSE 80

# provide defaults for an executing container
CMD ["nginx", "-g", "daemon off;"]
